[project]
name = "lukim-gather-server"
version = "0.1.0"
description = '"Lukim gather server"'
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.11,<4"
dependencies = [
    "Django>=4.2,<5",
    "environs[django]>=13,<14",
    "marshmallow>=3.14.1,<4",
    "psycopg2-binary>=2.9.3,<3",
    "graphene-django>=3.0.0b7,<4",
    "django-filter>=22.1,<23",
    "django-graphql-jwt>=0.3.4,<0.4.0",
    "celery>=5.2.3,<6",
    "redis>=5.2,<6",
    "django-modeltranslation>=0.18,<0.19",
    "django-ordered-model>=3.5.0,<4",
    "django-ckeditor>=6.2.0,<7",
    "django-mptt>=0.15,<0.16",
    "django-graphql-geojson>=0.1.4,<0.2",
    "graphene-file-upload>=1.3.0,<2",
    "sentry-sdk>=2.19,<3",
    "djangorestframework>=3.13.1,<4",
    "django-admin-autocomplete-filter>=0.7.1,<0.8",
    "djangorestframework-gis>=0.18,<0.19",
    "django-cors-headers>=4.4.0,<5",
    "pillow>=11,<12",
    "graphene-django-extras>=1.0.0,<2",
    "django-admin-interface>=0.29.0,<0.30",
    "django-json-widget>=2.0,<3",
    "django-oauth-toolkit>=3,<4",
    "django-allauth>=65.2.0,<66",
    "django-vectortiles>=1.0.0,<2",
    "boto3>=1.24.42,<2",
    "django-phonenumber-field[phonenumbers]>=7.1.0,<8",
    "watchtower>=3.0.0,<4",
    "django-ratelimit>=4.0.0,<5",
    "django-reversion>=5.0.3,<6",
    "django-push-notifications[WP, APNS]>=3.0.0,<4",
    "py3-validate-email>=1.0.5.post1,<2",
    "sorl-thumbnail>=12.10.0,<12.11.0",
    "django-ckeditor-5>=0.2.15,<0.3",
]

[project.optional-dependencies]
asgi = [
    "uvicorn[standard]>=0.32.0,<0.34",
    "gunicorn>=22.0.0,<23",
]

[dependency-groups]
dev = [
    "django-extensions>=3.1.5,<4",
    "pre-commit>=4,<5",
    "model-bakery>=1.4.0,<2",
    "werkzeug>=3.0.1,<4",
    "ruff>=0.9.6,<1",
]

[tool.ruff]
target-version = "py311"
exclude = ["*/migrations/*","__pycache__"]

[tool.ruff.lint]
extend-select = ["B008", "C4", "DJ", "FIX", "I", "Q", "S", "T10", "T20", "W"]

[tool.ruff.lint.isort]
combine-as-imports = true
