# Generated by Django 3.2.14 on 2022-08-15 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_organizations', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
