# Generated by Django 3.2.14 on 2022-08-23 06:22

from django.db import migrations, models
import lukimgather.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=lukimgather.fields.LowerEmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='organization',
            name='point_of_contact',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='point of contact'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
    ]
