# Generated by Django 3.2.15 on 2022-11-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220823_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
    ]
