# Generated by Django 4.2.19 on 2025-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organization_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='description'),
        ),
    ]
