# Generated by Django 3.2.12 on 2022-03-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('other', 'Other')], default='image', max_length=15, verbose_name='Media Type')),
                ('media', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Media File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
