# Generated by Django 3.2.13 on 2022-06-27 09:57

import uuid

from django.db import migrations, models


def generate_uuid(apps, schema_editor):
    Gallery = apps.get_model("gallery", "Gallery")
    for row in Gallery.objects.all():
        if hasattr(row, 'uuid'):
            row.uuid = uuid.uuid4()
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_options'),
    ]

    run_before = [
        ('survey', '0014_auto_20220628_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.RunPython(
            generate_uuid, reverse_code=migrations.RunPython.noop
        ),
    ]
