# Generated by Django 3.2.13 on 2022-06-29 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='id',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='uuid',
            new_name='id',
        ),
    ]
