# Generated by Django 3.2.13 on 2022-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_object_object_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='action object object id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor_object_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='actor object id'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_object_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='target object id'),
        ),
    ]
