# Generated by Django 3.2.23 on 2024-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_categoryactivitytrigger_contactemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryactivitytrigger',
            name='event',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved')], default='created', max_length=10, verbose_name='Event'),
        ),
    ]
