# Generated by Django 3.2.23 on 2024-06-04 08:19

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_survey_answer_sorted'),
        ('notification', '0006_categoryactivitytrigger_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryactivitytrigger',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_activity_triggers', to='survey.protectedareacategory'),
        ),
    ]
