# Generated by Django 4.2.19 on 2025-02-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_alter_categoryactivitytrigger_category"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_e8adee_idx",
            old_fields=("recipient", "has_read"),
        ),
    ]
