# Generated by Django 3.2.23 on 2024-09-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_logo'),
        ('notification', '0008_rename_notification_recipient_has_read_notificatio_recipie_e8adee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryactivitytrigger',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.project', verbose_name='project'),
        ),
    ]
