# Generated by Django 4.2.19 on 2025-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_rename_notification_recipient_has_read_notificatio_recipie_e8adee_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='description'),
        ),
    ]
