version: "3.7"

services:
  server:
    container_name: "${PROJECT_NAME}_server"
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - default
      - external-services
  celery_worker:
    container_name: "${PROJECT_NAME}_celery_worker"
    env_file: .env
    environment:
      CELERY_WORKER: "true"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/code
    networks:
      - default
      - external-services

networks:
  external-services:
    external: true
