# Generated by Django 3.2.14 on 2022-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20220830_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='icon'),
        ),
    ]
