# Generated by Django 4.2.19 on 2025-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_message',
            field=models.TextField(verbose_name='html message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer_ho',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='answer_tpi',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_ho',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='description_tpi',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_ho',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description_tpi',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='answer',
            field=models.TextField(verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='answer_ho',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='answer_tpi',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
    ]
