# Generated by Django 4.2.19 on 2025-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_comment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(),
        ),
    ]
