# Generated by Django 3.2.13 on 2022-05-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
