# Generated by Django 3.2.18 on 2023-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='project/logos', verbose_name='logo'),
        ),
    ]
