# Generated by Django 3.2.13 on 2022-06-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0003_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='organization',
            field=models.ManyToManyField(blank=True, to='organization.Organization', verbose_name='Organizations'),
        ),
    ]
