# Generated by Django 3.2.18 on 2023-04-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], default=None, max_length=15, null=True),
        ),
    ]
