# Generated by Django 3.2.23 on 2023-12-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_accept_reject_project', 'Can accept/reject project'),)},
        ),
    ]
