# Generated by Django 4.2.19 on 2025-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='description'),
        ),
    ]
