# Generated by Django 3.2.12 on 2022-04-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectedareacategory',
            options={'verbose_name_plural': 'Protected area categories'},
        ),
        migrations.AddField(
            model_name='localenviromentalsurvey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_enviromental_survey', to='survey.protectedareacategory'),
        ),
        migrations.AddField(
            model_name='protectedareacategory',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='code'),
        ),
    ]
