# Generated by Django 3.2.12 on 2022-04-20 09:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20220420_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='title_tpi',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='protectedareacategory',
            name='title_tpi',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_tpi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='question',
            name='hints_tpi',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='hints'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_tpi',
            field=models.TextField(null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='title_tpi',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
