# Generated by Django 3.2.12 on 2022-04-22 11:17

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_auto_20220420_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappeningSurvey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('sentiment', models.TextField(blank=True, default=None, null=True, verbose_name='Sentiments')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326, verbose_name='Location')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, default=None, null=True, srid=4326, verbose_name='Location Boundary')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=11, verbose_name='Happening Survey Answer Status')),
                ('data_dump', models.JSONField(blank=True, default=dict)),
                ('attachment', models.ManyToManyField(blank=True, to='gallery.Gallery', verbose_name='Attachments')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happening_survey', to='survey.protectedareacategory')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LocalEnviromentalSurvey',
        ),
    ]
