# Generated by Django 3.2.13 on 2022-04-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20220422_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='happeningsurvey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='happeningsurvey',
            name='improvement',
            field=models.CharField(blank=True, choices=[('increasing', 'Increasing'), ('same', 'Same'), ('decreasing', 'Decreasing')], default=None, max_length=11, null=True, verbose_name='Happening Survey Improvement Status'),
        ),
    ]
