# Generated by Django 3.2.13 on 2022-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20220503_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='option',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='group',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='form',
        ),
        migrations.RemoveField(
            model_name='questiongroup',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='surveyanswer',
            options={'verbose_name': 'Survey answer', 'verbose_name_plural': 'Survey answers'},
        ),
        migrations.RemoveConstraint(
            model_name='surveyanswer',
            name='unique_survey_question',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='answer_type',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='options',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='form',
            name='xform',
            field=models.JSONField(blank=True, default=dict, verbose_name='XForms'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer',
            field=models.JSONField(blank=True, default=dict, verbose_name='Survey answer'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
    ]
