# Generated by Django 3.2.13 on 2022-05-20 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
        ('survey', '0010_auto_20220510_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happening_survey', to='region.region'),
        ),
    ]
