# Generated by Django 3.2.13 on 2022-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_happeningsurvey_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
