# Generated by Django 3.2.13 on 2022-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_happeningsurvey_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
