# Generated by Django 3.2.13 on 2022-06-28 06:15

from django.db import migrations, models

def generate_uuid_happening_survey_gallery(apps, schema_editor):
    HappeningSurvey = apps.get_model('survey', 'HappeningSurvey')
    for row in HappeningSurvey.objects.exclude(attachment=None):
        if hasattr(row, 'attachment'):
            row.attachment_uuid = [str(attachment_uuid) for attachment_uuid in row.attachment.values_list('uuid', flat=True)]
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_happeningsurvey_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='attachment_uuid',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.RunPython(
            generate_uuid_happening_survey_gallery,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='happeningsurvey',
            name='attachment',
        ),
    ]
