# Generated by Django 3.2.13 on 2022-06-29 04:40
import ast

from django.db import migrations, models

def create_gallery_relations(apps, schema_editor):
    Gallery = apps.get_model('gallery', 'Gallery')
    HappeningSurvey = apps.get_model('survey', 'HappeningSurvey')
    for row in HappeningSurvey.objects.exclude(attachment_uuid=None):
        if hasattr(row, 'attachment_uuid'):
            gallery_obj = Gallery.objects.filter(id__in=ast.literal_eval(row.attachment_uuid))
            row.attachment.set(gallery_obj)
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20220629_0440'),
        ('survey', '0014_auto_20220628_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='gallery.Gallery', verbose_name='Attachments')),
        migrations.RunPython(
            create_gallery_relations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='happeningsurvey',
            name='attachment_uuid',
        ),
    ]
