# Generated by Django 3.2.13 on 2022-07-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_protectedarea'),
        ('survey', '0015_auto_20220629_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='protected_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happening_survey', to='region.protectedarea'),
        ),
    ]
