# Generated by Django 3.2.15 on 2022-11-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('survey', '0017_form_question_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
