# Generated by Django 3.2.18 on 2023-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_happeningsurvey_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='happeningsurvey',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Audio File'),
        ),
    ]
