# Generated by Django 4.2.19 on 2025-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_survey_answer_sorted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='description'),
        ),
    ]
